#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
spring:
    h2:
     console.enabled: true
     console.path: /h2

server:
  contextPath:   /auth
